workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: 20.18.0  # ✅ Updated to required version
      java: 11
      vars:
        PACKAGE_NAME: "io.metamask"
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
