workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "io.metamask"
      node: 16.20.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
